### ISSUE TITLE
Enable images in question content

### ISSUE THREAD

**Issue by leac** [h5p/h5p-multi-choice#11]
We would like to be able to add images to any component (semantic) of the question (question, answers, feedback, ...):
![editor-img](https://cloud.githubusercontent.com/assets/1826720/16917994/8e5400ae-4d0c-11e6-982f-7f2b3b737e23.png)

In order to do that, so far we've been altering the multichoice package: In `semantics.json` we add the `img` tag to the list of tags. For example:
```
{
    "name": "question",
    "type": "text",
    "widget": "html",
    "label": "Question",
    "enterMode": "p",
    "tags": [
      "strong",
      "img",
      "em",
      "sub",
      "sup",
      "h2",
      "h3"
    ]
  }
```

Please see if you can add this feature to the core.
(This request is part a bigger discussion already started on [issue](https://github.com/h5p/h5p-editor-php-library/issues/13)  )

**Comment by icc** [comment]
In an H5P context, the WYSIWYG is mostly intended for textual content and not as much for structure and visuals. Allowing images in the text would make the content more unpredictable and it will become more difficult to make changes to the content types without breaking anything. Ideally, the images that are needed should be added as separate fields.

Also, UX wise, I think it's preferable to create familiar patterns for the users.

I don't think this is something that will be including per default in H5P, but you are more than welcome to create 3rd party plugins that modifies the semantics and add support for it. 
I would not recommend modifying the content types directly as this would create 'corrupt' versions of the content types. In such case, you should fork the content type and give it a different name.

**Comment by nadavkav** [comment]
It seems to me that content creators (and their QA team) should be responsible for checking out the outcome of inserting images into content on different devices. making the UI more complicated by adding new input fields for images and their properties will render the editing UI too complex.

Anyways, I talked about this with @leac (offline) and I still think she and the pedagogical content creators are right. So I guess we will fork it, as we need this feature on many content contextes.

**Comment by falcon-git** [comment]
You don't need to fork it to add this. You may use the corresponding hooks to alter the semantics without forking, see this example for Drupal for instance: https://h5p.org/adding-text-editor-buttons

**Comment by nadavkav** [comment]
Thank you @falcon-git for the link. I read it, but did understand how to implement it in Moodle. I probably need to dive deeper into the H5P code. :smile:

**Comment by fnoks** [comment]
These hooks are not yet available in Moodle. They will be added in a later release.

**Comment by nadavkav** [comment]
Are you guys referring to these https://tracker.moodle.org/browse/MDL-44078 hooks?

**Comment by fnoks** [comment]
> Are you guys referring to these https://tracker.moodle.org/browse/MDL-44078 hooks?

@nadavkav: No, we are talking about this one: https://github.com/h5p/h5p-moodle-plugin/issues/26

**Comment by nadavkav** [comment]
wow! I was not aware of this.
Added my +1 to this feature.

On 9 Aug 2016 11:44, "Pål Jørgensen" <notifications@github.com> wrote:

Are you guys referring to these https://tracker.moodle.org/browse/MDL-44078
hooks?

@nadavkav <https://github.com/nadavkav>: No, we are talking about this one:
h5p/h5p-moodle-plugin#26
<https://github.com/h5p/h5p-moodle-plugin/issues/26>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/h5p/h5p-multi-choice/issues/11#issuecomment-238491233>,
or mute the thread
