### ISSUE TITLE
xAPI data response element empty when answer order not randomised.

### ISSUE THREAD

**Issue by OliverColeman** [h5p/h5p-multi-choice#16]
When answer order is not randomised the xAPI data response element is always empty. It looks like this line in multichoice.js (around 855):

`response += idMap === undefined ? $(params.userAnswers[i]).text() : idMap[params.userAnswers[i]];`

should be:

`response += idMap === undefined ? params.userAnswers[i] : idMap[params.userAnswers[i]];`

At least that works in my brief tests.

**Comment by tajakobsen** [comment]
I this as a bug in the Core Teams [Jira](https://h5ptechnology.atlassian.net/browse/HFP-402).
