### ISSUE TITLE
xAPI problems after updating to 1.3.2 (using Drupal)

### ISSUE THREAD

**Issue by foxylearning** [h5p/h5p-multi-choice#2]
After updating to 1.3.2 (using Drupal), I noticed that some custom javascript I use to handle H5P's xAPI statements stopped working. The xAPI event statement appears to work fine for initial selection of an option, but upon checking the answer, the statement does not appear to be generated or working correctly. Looking at the console, I see this error message:

TypeError: undefined is not an object (evaluating 'idMap[params.userAnswers[i]]')

**Comment by falcon-git** [comment]
Hi! Could you add a screenshot of that console log, or provide more of it as text? It contains information about which line of code the error comes from.

**Comment by foxylearning** [comment]
You can check it out yourself here (I have the event statement being written to the console on this page): https://foxylearning.com/tutorials/va/2/187475-6078

Also, I just realized that the event statement IS being generated, but it seems the results portion of it are not.

**Comment by falcon-git** [comment]
I'm sorry about that. It happend for all multichoices with random order disabled. If you upgrade to the latest version you should be fine. Thank you for reporting!

http://h5p.org/update-all-content-types
