### ISSUE TITLE
H5P Multi-choice does not work with IE11 browser 

### ISSUE THREAD

**Issue by hirvota** [h5p/h5p-multi-choice#22]
Multiple-choice does not open Option field with Expand/Collapse selection. This was experienced with H5P version 1.0-rc.8 and IE11 browser (11.0.9600.18537). Same behaviour exists on H5P.org  site when creating content  there.

Note! This used to work with H5P version 1.0-rc.7. 

![no option](https://cloud.githubusercontent.com/assets/25204824/23850891/0972cef8-07ea-11e7-9503-ffeb279f7a1a.png)

**Comment by falcon-git** [comment]
I believe this is fixed in 1.0 (stable) for Moodle
