### ISSUE TITLE
iOS Safari and Android Opera display problems on old iOS version

### ISSUE THREAD

**Issue by truonganhhoang** [h5p/h5p-multi-choice#8]
Question and answers are not shown

**Comment by falcon-git** [comment]
What version of iOS are you on? The current version should be tested on both iPad and iPhone.

**Comment by truonganhhoang** [comment]
The iOS is 8.3 and the browser is Safari. It is fine with Chrome on iOS 8.3.

**Comment by falcon-git** [comment]
Ok, I'm afraid we only support the newest version of iOS, but if someone wants to create patches for older versions we're happy to consider them.
